# For more information about the configurations used
# in this file, please see the Travis CI documentation.
# .travis.yml
# https://docs.travis-ci.com

sudo: enabled

install:
  - sudo bash -c "add-apt-repository -ys ppa:nilarimogard/webupd8 ; add-apt-repository -ys ppa:kelleyk/emacs"
  - sudo apt-get remove -yy emacs* || true; sudo apt install -yy emacs26-nox
  - sudo bash -c "$(curl -LSs https://github.com/dfmgr/installer/raw/main/install.sh)"
  - sudo pkmgr init && sudo pkmgr update
  - dfmgr install emacs
  - bash -c "[ -f $(command -v emacs >/dev/null 2>&1) ] && timeout --signal=9 --foreground --preserve-status 5 emacs || true"

matrix:
  include:
    - os: linux
      dist: bionic
      language: bash
      sudo: enabled

notifications:
  email:
    on_failure: never
    on_success: never
